#!/bin/bash

for dir in ./*/     # list directories
do
    dir=${dir%*/}      # remove the trailing "/"
    echo "## [${dir##*/}](${dir##*/}/)"    # print everything after the final "/"
    echo ""
    echo "### Description"
    echo ""
    cat ${dir##*/}/readme.txt
    echo ""
    echo ""
done
